name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  cypress-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Test
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev